repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '^.*swagger\.json$'
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        files: ^go-server/.*\.go$
        types: [file]
      - id: go-imports
        files: ^go-server/.*\.go$
        types: [file]
      - id: no-go-testing
        files: ^go-server/.*\.go$
        types: [file]

  - repo: local
    hooks:
    - id: custom-golangci-lint
      name: golangci-lint
      entry: sh -c 'cd go-server && golangci-lint run'
      language: system
      files: ^go-server/.*\.go$
      types: [file]
    - id: custom-go-unit-tests
      name: go-unit-tests
      entry: sh -c 'cd go-server && go test ./...'
      language: system
      files: ^go-server/.*\.go$
      types: [file]

  - repo: https://github.com/muya/swaggo-hooks
    rev: v1.1.1
    hooks:
      - id: swag-init
        files: ^go-server/
        args:
          - --generalInfo=go-server/cmd/main.go
          - --output=go-server/docs
